/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_fin_scanner_OpenCVHelper */

#ifndef _Included_my_fin_scanner_OpenCVHelper
#define _Included_my_fin_scanner_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_fin_scanner_OpenCVHelper
 * Method:    scan
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_my_fin_scanner_OpenCVHelper_scan
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
